admin.benuter.neu.jsp in AdministrationServlet eingearbeitet
ubtue/neg pull request #247
Opened 2024-09-03 08:16 UTC by rnaiser

ich habe die tabführung in administration verändert ich verwende nicht mehr die javascript funktion onoff(show, hide), denn wenn ich auf benutzer neu war und bei feher eingabe zurück wollte gab es mit dieser variante der tab führung nicht die möglichkeit auf tab2 zurück zugehen immer tab 1 , nicht schön.

Nun tut es perfekt.

2024-09-03 08:55 UTC, mtrojan-ub commented
Das ist schonmal ein guter erster Schritt. Mir fällt noch folgendes auf:

Unter Administration sind ja verschiedene Dinge zusammengefasst: 
- Benutzer verwalten
- Neuer Benutzer
- Auswahlfelder

Der hier geänderte Teil "Neuer Benutzer" verwendet das AdministrationServlet mit dem template admin.benutzer.neu.jsp
Der andere Teil "Benutzer verwalten" der zur selben Themengruppe gehört verwendet das EinstellungenServlet mit dem Template einstellungen.jsp

Daher würde ich Folgendes vorschlagen:
=> einstellungen.jsp umbenennen in admin.benutzer.bearbeiten.jsp
=> Das EinstellungenServlet löschen, für beide Teile das AdministrationServlet verwenden (die Alternative wäre dass man AdministrationServlet umbenennt in z.B.  AdministrationBenutzerAnlegenServlet und EinstellungenServlet in z.B. AdministrationBenutzerBearbeitenServlet, und am Ende haben wir dann für jede Aktion 1 Servlet => wahrscheinlich wäre es besser mehrere Aktionen für ähnliche Teilbereiche ins selbe Servlet zusammenzufassen). Dann sollte man in der generatePage nur noch auf die Aktion prüfen und dann die passende Logik zur Verarbeitung der Aktion in jeweils eine private Funktion verlagern (wenn die Templates separat bleiben fände ich das OK, das Servlet muss dann entscheiden für welche Aktion es welches Template lädt). Wichtige Frage ist aber ob das noch machbar ist weil einstellungen.jsp ja aktuell nicht nur für den Admin verwendet wird sondern auch wenn ein nicht-admin Benutzer sein eigenes Profil ändert.
=> Da unter "Administration" in der Oberfläche ja auch der Teil "Auswahlfelder" zu finden ist, stellt sich auch hier die Frage ob man die Logik ins AdministrationServlet übernimmt. 

Also zusammengefasst: Entweder macht man 1 großes AdministrationServlet und packt alles rein was tatsächlich auch im Menü mit Administration zu tun hat, oder (wenn das zu komplex ist) sorgt man zumindest dafür dass alle Servlets + Templates die es bereits in diesem Teilbereich gibt einheitlich benannt sind.

2024-09-03 08:57 UTC, mtrojan-ub requested changes
Siehe Kommentare im PR => zumindest bitte eine passende einheitliche Benennung verwenden für alle Servlets + Templates die im Backend unter Administration beteiligt sind.

(Man könnte auch alles in 1 großes Servlet packen aber das wäre um einiges aufwendiger.)

2024-09-12 07:56 UTC, mtrojan-ub commented on src/main/java/de/uni_tuebingen/ub/nppm/servlet/AjaxServlet.java
> +                Logger.getLogger(AjaxServlet.class.getName()).log(Level.SEVERE, null, ex);
Please implement the error handling in a similar way like the other functions do (e.g. confirmLemma). There you will see that the try/catch is directly there in the method, and there is a line that modifies the returned HTTP code:

response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);

So you should do that directly there instead of throwing an exception which you catch in doPost.
I like the idea with the log message, but that should also be generated inside the newParentNode function and not in doPost.

2024-09-12 10:38 UTC, rnaiser commented on src/main/java/de/uni_tuebingen/ub/nppm/servlet/AjaxServlet.java
> +                Logger.getLogger(AjaxServlet.class.getName()).log(Level.SEVERE, null, ex);
done

2024-09-12 10:44 UTC, mtrojan-ub commented on src/main/java/de/uni_tuebingen/ub/nppm/servlet/AjaxServlet.java
> +                Logger.getLogger(AjaxServlet.class.getName()).log(Level.SEVERE, null, ex);
As far as i can see the try/catch has been moved to the newParentNode function correctly, but the function still doesnt set a proper result status code in the catch block.

2024-09-12 12:31 UTC, rnaiser commented on src/main/java/de/uni_tuebingen/ub/nppm/servlet/AjaxServlet.java
> +                Logger.getLogger(AjaxServlet.class.getName()).log(Level.SEVERE, null, ex);
done

2024-09-12 12:58 UTC, merged